[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.filesystem = littlefs
lib_deps = 
	mathieucarbou/ESPAsyncWebServer@^3.6.0
	bblanchon/ArduinoJson@^7.0.4
	knolleary/PubSubClient@^2.8.0
board_build.partitions = partitions.csv
